### ISSUE TITLE
Segmentation fault in kunzip

### ISSUE THREAD

**Issue by mattix** [dstosberg/odt2txt#7]
Program received signal SIGSEGV, Segmentation fault.
0x000000000040445a in read_chars (in=0x637d90, s=0x0, count=-256) at kunzip/fileio.c:44
44		s[t] = 0;

#0  0x000000000040445a in read_chars (in=0x637d90, s=0x0, count=-256) at kunzip/fileio.c:44
#1  0x0000000000404be0 in kunzip_get_offset_by_name (zip_filename=0x7fffffffea27 "testi.odt", compressed_filename=0x40591e "content.xml", 
    match_flags=3, skip_offset=-1) at kunzip/zipfile.c:264
#2  0x0000000000401a76 in read_from_zip (zipfile=0x7fffffffea27 "testi.odt", filename=0x40591e "content.xml") at odt2txt.c:405
#3  0x0000000000402356 in main (argc=2, argv=0x7fffffffe718) at odt2txt.c:566

File used: https://dl.dropboxusercontent.com/u/58596243/sample.odt

Oh. If you think how in earth I did discover this it was an assignment using American Fuzzy Lop -fuzzer.

**Comment by dstosberg** [comment]
Yes, this was an easy and obvious error in the kunzip part. There were no sanity checks for the length fields read from the zip header. I fixed this case, but I'm pretty sure that there are other ways to trigger errors by using corrupt files.

There is _usually_ no reason to prefer kunzip over the tested and more sophisticated external libzip. I did what I should have done long ago: I made libzip the default option and added a warning for those folks still using kunzip.

I will not remove the kunzip part for now, because from time to time I hear from people using odt2txt on DOS and I'm not sure that libzip can be built there.

I will close this issue for now. I will not actively search further errors or corner cases in kunzip. If you find further problems, please feel free to open a new issue and we'll see how to handle it.

Cheers,
Dennis
